package com.example.noteapp.model

enum class Category {
    AGE, ALONE, AMAZING, ANGER, ARCHITECTURE, ART, ATTITUDE, BEAUTY, BEST, BIRTHDAY,
    BUSINESS, CAR, CHANGE, COMMUNICATION, COMPUTERS, COOL, COURAGE, DAD, DATING, DEATH,
    DESIGN, DREAMS, EDUCATION, ENVIRONMENTAL, EQUALITY, EXPERIENCE, FAILURE, FAITH, FAMILY,
    FAMOUS, FEAR, FITNESS, FOOD, FORGIVENESS, FREEDOM, FRIENDSHIP, FUNNY, FUTURE, GOD, GOOD,
    GOVERNMENT, GRADUATION, GREAT, HAPPINESS, HEALTH, HISTORY, HOME, HOPE, HUMOR, IMAGINATION,
    INSPIRATIONAL, INTELLIGENCE, JEALOUSY, KNOWLEDGE, LEADERSHIP, LEARNING, LEGAL, LIFE, LOVE,
    MARRIAGE, MEDICAL, MEN, MOM, MONEY, MORNING, MOVIES, SUCCESS
}
